const { readdirSync, writeFileSync } = require('fs');

const TARGET_DIR = './src/components/CryptocurrencyIcon';
const TARGET_FILE = `${TARGET_DIR}/get-dynamic-icon.ts`;
const ICON_SOURCE_DIR = './node_modules/cryptocurrency-icons/react';

const generateCurrencyIcons = () => {
  const icons = readdirSync(ICON_SOURCE_DIR);
  const content = icons
    .map(iconFile => {
      const [fileName] = iconFile.split('.');
      // add alternate icon name for the 'index' icon
      const iconName = fileName === 'index' ? 'indexIcon' : fileName;
      return `    case '${iconName}':
      return lazy(() => import('cryptocurrency-icons/react/${iconName}'));`;
    })
    .join('\n');
  const template = `/* eslint-disable */
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED BY /scripts/generate-currency-icons.
import { lazy } from 'react';
export const getDynamicIcon = (name: string) => {
  switch (name) {
${content}
    default:
      return null;
  }
};
`;
  writeFileSync(TARGET_FILE, template);
};

generateCurrencyIcons();
