name: Jest Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Run Jest tests
        run: yarn test
