name: Storybook Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Storybook tests
        run: npm run storybook:test:ci
